---
 - name: var test
   hosts: all
   vars_file: group_var
   tasks:
     - name: create '{{ user }}'
       user:
         name: '{{ user }}'
         state: present
     - name: create '{{ grp }}'
       group:
         name: '{{ grp }}'
       state: present
     - name: install '{{ pkg }}'
       yum:
         name: '{{ pkg }}'
         state: latest

